import { ScenarioPreset } from '../types';

export const SCENARIOS: ScenarioPreset[] = [
  {
    key: 'sales',
    label: '営業トーク',
    description: '家賃維持・空室ゼロ・価格下落なし。よくある説明資料の前提',
    annualRentChangeRate: 0.0,
    vacancyRate: 1.0,
    annualInterestRate: 0.8,
    annualCostGrowthRate: 0.0,
    annualPriceChangeRate: 0.0,
    repairReserveMonthly: 3000,
    majorRepairCost: 100000,
  },
  {
    key: 'optimistic',
    label: '楽観',
    description: '東京・大阪都心の主要駅徒歩5分以内・築10年以内の超好立地物件に限定した想定。家賃・資産価値ともに年0.5%上昇。全国のワンルーム投資の大多数には当てはまりません',
    annualRentChangeRate: -0.5,
    vacancyRate: 3.0,
    annualInterestRate: 1.2,
    annualCostGrowthRate: 0.5,
    annualPriceChangeRate: -0.5,
    repairReserveMonthly: 4000,
    majorRepairCost: 200000,
  },
  {
    key: 'base',
    label: '標準',
    description: '現実寄りのベースケース',
    annualRentChangeRate: 1.0,
    vacancyRate: 8.0,
    annualInterestRate: 1.8,
    annualCostGrowthRate: 1.0,
    annualPriceChangeRate: 1.0,
    repairReserveMonthly: 5000,
    majorRepairCost: 300000,
  },
  {
    key: 'pessimistic',
    label: '悲観',
    description: '空室・下落・コスト増を強めに想定',
    annualRentChangeRate: 2.0,
    vacancyRate: 15.0,
    annualInterestRate: 2.8,
    annualCostGrowthRate: 2.0,
    annualPriceChangeRate: 2.0,
    repairReserveMonthly: 10000,
    majorRepairCost: 600000,
  },
];
